### ISSUE TITLE
Let's bring everything together into the bnomial repo

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#147]
@haltakov What is your suggestion to create a single repo for the project?

**Comment by haltakov** [comment]
I'm a fan of a monorepos :) Let me summarize how I imagine the structure of the repo:

`bnomial`
\- `api` - this folder will contain the code for the backend API(s)
\- `daily-question` - this folder will contain the code for the daily question website
\- `web3`- this folder will contain the code for the token and NFT
\- `<potential future website>` - if we decide to build another interface to the bnomial API we can create a separate folder 

The advantages of this approach:
- We can guarantee that the versions of the different parts are synced, especially the API interface between the frontend and the backend.
- We can create pull requests adapting two parts of the project synchronously (for example adapting the API interface and fixing the frontend code to use it).
- We can always create new projects, by adding separate folders to the root. They may be different websites or different APIs using the same DB.
- We can easily have the CI configured to run different jobs for different folders.
- In the future, we can have different CODEOWNERS for different folders if we want finer control over the merge rights.

The disadvantage of this approach:
- If you work only on one part of the project, you still need to check out all the code and always pull all the changes. This can be annoying for very large repos, but our case is much simpler (I work on a monorepo with more than 1000 devs at work and it is only a minor inconvenience).
- A one-time overhead to migrate everything.

In my opinion, the small overhead of having everything in the same repo is worth it because we can keep everything in sync much easier. And it is important to not treat one repo as one project - you can have different "projects" in the same repo with different CIs, different deployment tools and different code owners.

**Comment by haltakov** [comment]
Done
